### PR TITLE
Math Magicians: setup

### PR DESCRIPTION
**Pull request by AdnanOlarmmi**
# Math Magicians: setup

- Hi reviewer,
Patrick Hi

## Learning objectives

- Set up a React app.
- Use React documentation.

## Description

This is the first project of the *Math Magicians* application. I set up the environment and tools needed to develop a React application. In the following projects, I will develop the actual application.

### General requirements

- Made sure that there are [no linter errors](https://github.com/microverseinc/linters-config). **Remember that this is your first React project and it requires a special linters setup. Check the instructions in the linters-config README.**
- Made sure to use correct [Gitflow](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/git-github/articles/gitflow.md).
- Made sure to document work [in a professional way](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/articles/professional_repo_rules.md).

### JavaScript requirements

- Followed the list of [best practices for JavaScript](https://github.com/microverseinc/curriculum-html-css/blob/main/articles/javascript_best_practices.md).

## Work and submission mode

- Submitted **individually.**

## Appreciation
- Thanks for the review, it means a lot 🙃

### CODE REVIEW

**Review by GzimAsani — APPROVED** [review]
# STATUS: APPROVED :100:         
## There is nothing else to say than it's time to merge... :partying_face: 
Cheers and Happy coding! :clap:  :computer:  :wine_glass: 
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


## Optional suggestions
-N/A

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- 

### Please be reminded to not open a new pull request after you get a review, only use the same one :thought_balloon: 


 **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
 
 _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

**Comment by AdnanOlarmmi** [comment]
Thanks @GzimAsani  🙃

**Comment by AdnanOlarmmi** [comment]
Hi @GzimAsani Please, for the next task we're being told to use class based component and eslint is rejecting it as an error, should I just tell eslint to ignore the line? 🙂

**Comment by GzimAsani** [comment]
@AdnanOlarmmi , yes set it to ignore, if there is not another error

**Comment by AdnanOlarmmi** [comment]
Alright 😊 thank you @GzimAsani, I really appreciate your response.

**Pull request merged**
